# Generated by Django 2.2.5 on 2019-11-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture', models.CharField(max_length=20, verbose_name='遊びたい地域')),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='あなたの名前')),
                ('userid', models.IntegerField(verbose_name='ID')),
                ('game', models.CharField(default='', max_length=100, verbose_name='プレイしたいボードゲームやジャンル')),
                ('place', models.CharField(max_length=100, verbose_name='遊びたいカフェや場所')),
                ('date', models.DateField(verbose_name='遊びたい日時')),
                ('comment', models.TextField(max_length='400', verbose_name='その他コメントなど')),
                ('area', models.ManyToManyField(to='user_auth.Prefecture', verbose_name='遊びたい地域（県）')),
            ],
        ),
    ]
