# Generated by Django 2.2.5 on 2019-11-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.IntegerField(verbose_name='参加者のtwitterID')),
            ],
        ),
        migrations.AddField(
            model_name='recruitment',
            name='number',
            field=models.IntegerField(default=2, verbose_name='募集人数'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='participant',
            field=models.ManyToManyField(to='user_auth.Participants'),
        ),
    ]
